// packages/web-solid/src/components/todo/todo-severity.tsx
import type { JSX } from "solid-js";

import styles from "./todo-severity.module.css";
import { components } from "~/openapi/schema";
import {
  mdiAlert,
  mdiAlertOctagram,
  mdiHelpRhombus,
  mdiInformation,
} from "@mdi/js";
import { ElmMdiIcon } from "@elmethis/solid";

type Severity = components["schemas"]["ToDoSeverityResponse"];

export interface TodoSeverityProps {
  class?: string;

  style?: JSX.CSSProperties;

  severity: Severity;
}

const MAP: Record<
  Severity,
  {
    className: string;
    d: string;
  }
> = {
  UNKNOWN: {
    className: styles.unknown,
    d: mdiHelpRhombus,
  },
  DEBUG: {
    className: styles.debug,
    d: mdiAlertOctagram,
  },
  INFO: {
    className: styles.info,
    d: mdiInformation,
  },
  WARN: {
    className: styles.warn,
    d: mdiAlert,
  },
  ERROR: {
    className: styles.error,
    d: mdiAlertOctagram,
  },
};

export const TodoSeverity = (props: TodoSeverityProps) => {
  return (
    <span
      class={`${styles["todo-severity"]} ${MAP[props.severity].className} ${props.class ?? ""}`}
      style={props.style}
    >
      <ElmMdiIcon d={MAP[props.severity].d} class={styles.icon} />
      <span class={styles.text}>{props.severity}</span>
    </span>
  );
};

// packages/components/src/components/todo/ToDoSeverity.vue
<template>
  <div
    :class="$style.severity"
    :style="{
      '--color': ICON_MAP[level].color,
    }"
  >
    <ElmMdiIcon
      :d="ICON_MAP[level].icon"
      :color="ICON_MAP[level].color"
      size="1.25rem"
    />
    <ElmInlineText :text="level" />
  </div>
</template>

<script setup lang="ts">
import { ElmInlineText, ElmMdiIcon } from "@elmethis/vue";
import {
  mdiAlert,
  mdiAlertOctagon,
  mdiCrosshairsQuestion,
  mdiInformation,
} from "@mdi/js";

export interface ToDoSeverityProps {
  level: "Unknown" | "Info" | "Warn" | "Error";
}

const ICON_MAP: Record<
  ToDoSeverityProps["level"],
  {
    icon: string;
    color: string;
  }
> = {
  Unknown: {
    icon: mdiCrosshairsQuestion,
    color: "#9771bd",
  },
  Info: {
    icon: mdiInformation,
    color: "#6987b8",
  },
  Warn: {
    icon: mdiAlert,
    color: "#b69545",
  },
  Error: {
    icon: mdiAlertOctagon,
    color: "#c56565",
  },
};

withDefaults(defineProps<ToDoSeverityProps>(), {});
</script>

<style module lang="scss">
.severity {
  display: inline-flex;
  justify-content: flex-start;
  align-items: center;
  gap: 0.25rem;
  padding: 0.25rem;
  border: 1px solid var(--color);
  border-radius: 0.125rem;
  user-select: none;
}
</style>
