// packages/web-qwik/src/components/todo/todo-form.tsx
import {
  $,
  component$,
  QRL,
  useSignal,
  type CSSProperties,
} from "@qwik.dev/core";

import styles from "./todo-form.module.css";
import {
  ElmButton,
  ElmInlineText,
  ElmMdiIcon,
  ElmSelect,
  ElmTextField,
  type ElmSelectOption,
} from "@elmethis/qwik";
import { components } from "~/openapi/schema";
import { mdiSend } from "@mdi/js";

type Severity = components["schemas"]["ToDoSeverityResponse"];

export interface TodoFormProps {
  class?: string;

  style?: CSSProperties;

  submit$: QRL<
    (t: {
      title: string;
      severity: Severity;
      deadline?: string;
    }) => Promise<void>
  >;
}

export const TodoForm = component$<TodoFormProps>(
  ({ class: className, style, submit$ }) => {
    const options: ElmSelectOption[] = (
      ["UNKNOWN", "DEBUG", "INFO", "WARN", "ERROR"] as const
    ).map((severity) => ({
      id: severity,
      label: severity,
    }));

    const title = useSignal("");
    const selectedSeverity = useSignal<Severity>("INFO");
    const deadline = useSignal<string>("");
    const isLoading = useSignal(false);
    const error = useSignal<string | null>(null);

    const handleSubmit = $(async () => {
      isLoading.value = true;
      error.value = null;

      try {
        await submit$({
          title: title.value,
          severity: selectedSeverity.value,
          deadline: deadline.value === "" ? undefined : deadline.value,
        });
        title.value = "";
        selectedSeverity.value = "INFO";
        deadline.value = "";
      } catch (e) {
        if (e instanceof Error) {
          error.value = e.message;
        } else {
          error.value = String(e);
        }
      } finally {
        isLoading.value = false;
      }
    });

    return (
      <div class={[styles.wrapper, className]} style={style}>
        <div class={[styles["todo-form-kit"], className]} style={style}>
          <ElmSelect
            class={styles["severity-select"]}
            label="Severity"
            options={options}
            selectedOptionId={selectedSeverity}
            isLoading={isLoading.value}
          />
          <ElmTextField
            class={styles["title-input"]}
            label="Title"
            value={title}
            isLoading={isLoading.value}
          />
          <input
            class={styles["deadline-input"]}
            type="date"
            value={deadline.value}
            onInput$={(e) =>
              (deadline.value = (e.target as HTMLInputElement).value)
            }
          />
          <ElmButton
            class={styles["submit-button"]}
            onClick$={handleSubmit}
            isLoading={isLoading.value}
            disabled={title.value.trim() === ""}
          >
            <ElmMdiIcon d={mdiSend} />
          </ElmButton>
        </div>

        <div class={styles["todo-error"]}>
          {error.value && (
            <ElmInlineText color="#c56565">Error: {error.value}</ElmInlineText>
          )}
        </div>
      </div>
    );
  },
);

// packages/web-solid/src/components/todo/todo-form.tsx
import { createSignal, Show, type JSX } from "solid-js";

import styles from "./todo-form.module.css";
import {
  ElmButton,
  ElmInlineText,
  ElmMdiIcon,
  ElmSelect,
  ElmTextField,
  type ElmSelectOption,
} from "@elmethis/solid";
import { components } from "~/openapi/schema";
import { mdiSend } from "@mdi/js";

type Severity = components["schemas"]["ToDoSeverityResponse"];
const SEVERITIES = ["UNKNOWN", "DEBUG", "INFO", "WARN", "ERROR"] as const;
const OPTIONS: ElmSelectOption[] = SEVERITIES.map((severity) => ({
  id: severity,
  label: severity,
}));

export interface TodoFormProps {
  class?: string;

  style?: JSX.CSSProperties;

  submit: (todo: {
    title: string;
    severity: Severity;
    deadline?: string;
  }) => Promise<void>;
}

export const TodoForm = (props: TodoFormProps) => {
  const [title, setTitle] = createSignal("");
  const [selectedSeverity, setSelectedSeverity] =
    createSignal<Severity>("INFO");
  const [deadline, setDeadline] = createSignal("");
  const [isLoading, setIsLoading] = createSignal(false);
  const [error, setError] = createSignal<string | null>(null);

  const submit = async () => {
    if (isLoading()) {
      return;
    }
    setIsLoading(true);
    setError(null);

    try {
      await props.submit({
        title: title(),
        severity: selectedSeverity(),
        deadline: deadline() === "" ? undefined : deadline(),
      });
      setTitle("");
      setSelectedSeverity("INFO");
      setDeadline("");
    } catch (e) {
      if (e instanceof Error) {
        setError(e.message);
      } else {
        setError(String(e));
      }
    } finally {
      setIsLoading(false);
    }
  };

  const handleSubmit: JSX.EventHandler<HTMLFormElement, SubmitEvent> = (
    event,
  ) => {
    event.preventDefault();
    void submit();
  };

  return (
    <div class={`${styles.wrapper} ${props.class ?? ""}`} style={props.style}>
      <form
        class={`${styles["todo-form-kit"]} ${props.class ?? ""}`}
        style={props.style}
        onSubmit={handleSubmit}
      >
        <ElmSelect
          class={styles["severity-select"]}
          label="Severity"
          options={OPTIONS}
          selectedOptionId={selectedSeverity()}
          onSelectedOptionIdChange={(value) => {
            if (SEVERITIES.includes(value as Severity)) {
              setSelectedSeverity(value as Severity);
            }
          }}
          isLoading={isLoading()}
        />
        <ElmTextField
          class={styles["title-input"]}
          label="Title"
          value={title()}
          onInput={(event) => setTitle(event.currentTarget.value)}
          isLoading={isLoading()}
        />
        <input
          class={styles["deadline-input"]}
          type="date"
          aria-label="Deadline"
          value={deadline()}
          onInput={(event) => setDeadline(event.currentTarget.value)}
        />
        <ElmButton
          type="submit"
          class={styles["submit-button"]}
          aria-label="Create todo"
          isLoading={isLoading()}
          disabled={title().trim() === ""}
        >
          <ElmMdiIcon d={mdiSend} />
        </ElmButton>
      </form>

      <div class={styles["todo-error"]}>
        <Show when={error()} keyed>
          {(message) => (
            <ElmInlineText color="#c56565">Error: {message}</ElmInlineText>
          )}
        </Show>
      </div>
    </div>
  );
};
