// packages/web-solid/src/components/common/header.tsx
import {
  ElmMdiIcon,
  ElmSquareLoadingIcon,
  ElmToggleTheme,
} from "@elmethis/solid";
import { mdiLogin, mdiLogout } from "@mdi/js";
import { A } from "@solidjs/router";
import { For, Match, Show, Switch, type JSX } from "solid-js";

import type { SessionState } from "~/context/auth-context";
import styles from "./header.module.css";

export interface HeaderProps {
  class?: string;
  style?: JSX.CSSProperties;
  links: Array<{ d: string; href: string; label: string; native?: boolean }>;
  state: SessionState;
  onSignIn: () => void;
  onSignOut: () => void;
}

export const Header = (props: HeaderProps) => (
  <header
    class={`${styles.header}${props.class ? ` ${props.class}` : ""}`}
    style={props.style}
  >
    <nav class={styles["link-container"]} aria-label="Main navigation">
      <For each={props.links}>
        {(link) => (
          <Show
            when={link.native}
            fallback={
              <A class={styles.link} href={link.href} aria-label={link.label}>
                <ElmMdiIcon d={link.d} size="1.75rem" color="#937f69" />
              </A>
            }
          >
            <a class={styles.link} href={link.href} aria-label={link.label}>
              <ElmMdiIcon d={link.d} size="1.75rem" color="#937f69" />
            </a>
          </Show>
        )}
      </For>
    </nav>

    <div class={styles["link-container"]}>
      <button
        type="button"
        class={styles.link}
        aria-label={props.state === "login" ? "Sign out" : "Sign in"}
        disabled={props.state === "pending"}
        onClick={() =>
          props.state === "login" ? props.onSignOut() : props.onSignIn()
        }
      >
        <Switch>
          <Match when={props.state === "pending"}>
            <ElmSquareLoadingIcon size="1.75rem" />
          </Match>
          <Match when={props.state === "login"}>
            <ElmMdiIcon d={mdiLogout} size="1.75rem" color="#be5252" />
          </Match>
          <Match when={props.state === "logout"}>
            <ElmMdiIcon d={mdiLogin} size="1.75rem" color="#6987b8" />
          </Match>
        </Switch>
      </button>
      <ElmToggleTheme />
    </div>
  </header>
);

// packages/web-qwik/src/components/common/header.tsx
import { component$, QRL, type CSSProperties } from "@qwik.dev/core";

import styles from "./header.module.css";
import {
  ElmMdiIcon,
  ElmSquareLoadingIcon,
  ElmToggleTheme,
} from "@elmethis/qwik";
import { mdiLogin, mdiLogout } from "@mdi/js";

export interface HeaderProps {
  class?: string;

  style?: CSSProperties;

  links: Array<{
    d: string;
    onClick$: QRL<() => void>;
  }>;

  state: "pending" | "login" | "logout";

  handleSignInClick$: QRL<(...args: any[]) => Promise<void>>;
  handleSignOutClick$: QRL<(...args: any[]) => Promise<void>>;
}

export const Header = component$<HeaderProps>(
  ({
    class: className,
    style,
    links,
    state,
    handleSignInClick$,
    handleSignOutClick$,
  }) => {
    return (
      <header class={[styles["header"], className]} style={style}>
        <div class={styles["link-container"]}>
          {links.map((link, index) => (
            <div class={styles["link"]} key={index} onClick$={link.onClick$}>
              <ElmMdiIcon d={link.d} size="1.75rem" color="#937f69" />
            </div>
          ))}
        </div>

        <div class={styles["link-container"]}>
          <div
            class={styles["link"]}
            onClick$={
              state === "login" ? handleSignOutClick$ : handleSignInClick$
            }
          >
            {state === "pending" ? (
              <ElmSquareLoadingIcon size="1.75rem" />
            ) : state === "login" ? (
              <ElmMdiIcon d={mdiLogout} size="1.75rem" color="#be5252" />
            ) : (
              <ElmMdiIcon d={mdiLogin} size="1.75rem" color="#6987b8" />
            )}
          </div>
          <ElmToggleTheme />
        </div>
      </header>
    );
  },
);
