// packages/web-solid/src/components/common/signin.tsx
import {
  ElmButton,
  ElmHeading,
  ElmInlineText,
  ElmMdiIcon,
  ElmTextField,
} from "@elmethis/solid";
import { mdiSend } from "@mdi/js";
import { createEffect, createSignal, Show, type JSX } from "solid-js";

import styles from "./signin.module.css";

export interface SigninProps {
  class?: string;
  style?: JSX.CSSProperties;
  isLoading: boolean;
  isDisabled: boolean;
  error?: string | null;
  onSubmit: (username: string, password: string) => void | Promise<void>;
}

export const Signin = (props: SigninProps) => {
  const [username, setUsername] = createSignal("");
  const [password, setPassword] = createSignal("");
  const [innerError, setInnerError] = createSignal<string | null>(null);

  createEffect(() => setInnerError(props.error ?? null));

  const handleSubmit: JSX.EventHandler<HTMLFormElement, SubmitEvent> = (
    event,
  ) => {
    event.preventDefault();
    if (!username() || !password()) {
      setInnerError("Username and password are required.");
      return;
    }
    setInnerError(null);
    void props.onSubmit(username(), password());
  };

  return (
    <form
      class={`${styles.signin}${props.class ? ` ${props.class}` : ""}`}
      style={props.style}
      onSubmit={handleSubmit}
    >
      <ElmHeading level={1}>Sign In</ElmHeading>
      <ElmTextField
        label="username"
        value={username()}
        autocomplete="username"
        isLoading={props.isLoading}
        disabled={props.isDisabled}
        onInput={(event) => setUsername(event.currentTarget.value)}
      />
      <ElmTextField
        label="password"
        value={password()}
        autocomplete="current-password"
        isPassword
        isLoading={props.isLoading}
        disabled={props.isDisabled}
        onInput={(event) => setPassword(event.currentTarget.value)}
      />
      <ElmButton
        type="submit"
        block
        isLoading={props.isLoading}
        disabled={props.isDisabled}
      >
        <ElmMdiIcon d={mdiSend} />
        Sign In
      </ElmButton>
      <Show when={innerError()}>
        {(error) => (
          <ElmInlineText class={styles.error} color="#c56565">
            {error()}
          </ElmInlineText>
        )}
      </Show>
    </form>
  );
};

// packages/web-qwik/src/components/common/signin.tsx
import {
  $,
  component$,
  useSignal,
  useTask$,
  type CSSProperties,
  type QRL,
} from "@qwik.dev/core";

import styles from "./signin.module.css";
import {
  ElmButton,
  ElmHeading,
  ElmInlineText,
  ElmMdiIcon,
  ElmTextField,
} from "@elmethis/qwik";
import { mdiSend } from "@mdi/js";

export interface SigninProps {
  class?: string;

  style?: CSSProperties;

  isLoading: boolean;
  isDisabled: boolean;

  error?: string | null;

  onSubmit$: QRL<(username: string, password: string) => void>;
}

export const Signin = component$<SigninProps>((props) => {
  const { class: className, style, isLoading, isDisabled, onSubmit$ } = props;
  const username = useSignal("");
  const password = useSignal("");
  const innerError = useSignal<string | null>(null);

  useTask$(({ track }) => {
    const e = track(() => props.error);
    innerError.value = e ? e : null;
  });

  const handleClick = $(() => {
    if (!username.value || !password.value) {
      innerError.value = "Username and password are required.";
      return;
    } else {
      innerError.value = null;
    }

    onSubmit$(username.value, password.value);
  });

  return (
    <div class={[styles["signin"], className]} style={style}>
      <ElmHeading level={1}>Sign In</ElmHeading>
      <ElmTextField
        label="username"
        value={username}
        isLoading={isLoading}
        disabled={isDisabled}
      />
      <ElmTextField
        label="password"
        value={password}
        isPassword
        isLoading={isLoading}
        disabled={isDisabled}
      />
      <ElmButton
        block
        isLoading={isLoading}
        disabled={isDisabled}
        onClick$={handleClick}
      >
        <ElmMdiIcon d={mdiSend} />
        Sign In
      </ElmButton>

      <ElmInlineText class={styles["error"]} color="#c56565">
        {innerError.value}
      </ElmInlineText>
    </div>
  );
});
