// packages/web-solid/src/routes/anki/index.tsx
import { Meta, Title } from "@solidjs/meta";
import { createMemo, type JSX } from "solid-js";

import { AnkiReviewer, type AnkiCard } from "~/components/anki/anki-reviewer";
import { useAnki } from "~/context/anki-context";

export interface IndexProps {
  class?: string;
  style?: JSX.CSSProperties;
}

export default function AnkiRoute(props: IndexProps) {
  const anki = useAnki();

  const currentAnki = createMemo(() =>
    anki.state.ankiList.currentIndex != null
      ? anki.state.ankiList.data[anki.state.ankiList.currentIndex]
      : null,
  );

  const card = createMemo<AnkiCard | null>(() => {
    const item = currentAnki();
    if (!item) return null;
    return {
      pageId: item.metadata.page_id,
      url: item.metadata.url,
      isReviewRequired: item.metadata.is_review_required,
      loading: item.loading,
      block: item.block,
    };
  });

  const queueCount = createMemo(() => anki.state.ankiList.data.length);

  const shouldLearnCount = createMemo(() => {
    const now = new Date();
    return anki.state.ankiList.data.reduce(
      (acc, { metadata }) =>
        new Date(metadata.next_review_at) <= now ? acc + 1 : acc,
      0,
    );
  });

  const open = () => {
    const url = currentAnki()?.metadata.url;
    if (!url) return;
    const a = document.createElement("a");
    a.href = url;
    a.target = "_blank";
    a.rel = "noopener noreferrer";
    a.click();
  };

  const rate = (rating: number) => {
    const pageId = currentAnki()?.metadata.page_id;
    if (pageId) return anki.updateByRating(pageId, rating);
  };

  return (
    <>
      <Title>Anki | Internal</Title>
      <Meta name="description" content="Review and manage Anki cards" />
      <AnkiReviewer
        class={props.class}
        style={props.style}
        card={card()}
        queueCount={queueCount()}
        shouldLearnCount={shouldLearnCount()}
        createLoading={anki.state.create.loading}
        reviewLoading={anki.state.review.loading}
        onEdit={open}
        onCreate={anki.create}
        onReview={anki.review}
        onRefresh={() => anki.fetchBlock(currentAnki()?.metadata.page_id, true)}
        onRate={rate}
      />
    </>
  );
}

// packages/web-qwik/src/routes/anki/index.tsx
import {
  $,
  component$,
  useComputed$,
  useContext,
  useSignal,
  type CSSProperties,
} from "@builder.io/qwik";

import styles from "./anki.module.css";
import { AnkiContext } from "~/context/anki-context";
import {
  ElmBlockFallback,
  ElmButton,
  ElmInlineText,
  ElmJarkup,
  ElmMdiIcon,
} from "@elmethis/qwik";
import {
  mdiAlertDecagram,
  mdiBookEdit,
  mdiCircleSmall,
  mdiCreation,
  mdiMessageAlertOutline,
  mdiMessageCheckOutline,
  mdiMessageQuestionOutline,
  mdiRefresh,
  mdiSchool,
  mdiTrayFull,
} from "@mdi/js";

export interface IndexProps {
  class?: string;

  style?: CSSProperties;
}

export default component$<IndexProps>(({ class: className, style }) => {
  const ankiStore = useContext(AnkiContext);

  const currentAnki = useComputed$(() =>
    ankiStore.ankiList.currentIndex != null
      ? ankiStore.ankiList.data[ankiStore.ankiList.currentIndex]
      : null,
  );

  const isShowingAnswer = useSignal(false);

  const handleUpdate = $((pageId?: string, performanceRating?: number) => {
    if (!ankiStore.updateAnkiByPerformanceRating) return;
    if (!pageId || !performanceRating) return;

    ankiStore.updateAnkiByPerformanceRating(
      ankiStore,
      pageId,
      performanceRating,
    );

    if (currentAnki.value?.metadata.page_id === pageId) {
      isShowingAnswer.value = false;
    }
  });

  const count = useComputed$(() => ankiStore.ankiList.data.length);

  const shouldLearnCount = useComputed$(() => {
    const now = new Date();
    const count = ankiStore.ankiList.data.reduce((acc, { metadata }) => {
      if (
        metadata.is_review_required ||
        (metadata.next_review_at && new Date(metadata.next_review_at) <= now)
      ) {
        return acc + 1;
      }
      return acc;
    }, 0);
    return count;
  });

  const open = $(() => {
    const a = document.createElement("a");
    if (!currentAnki.value?.metadata.url) return;
    a.href = currentAnki.value?.metadata.url.replace(
      /https?:\/\//,
      "notion://",
    );
    a.target = "_blank";
    a.rel = "noopener noreferrer";
    a.click();
  });

  return (
    <div
      class={[styles["anki"], className]}
      style={style}
      key={String(currentAnki?.value?.loading)}
    >
      <div class={styles["button-control"]}>
        <ElmButton block onClick$={open} loading={currentAnki.value == null}>
          <ElmMdiIcon d={mdiBookEdit} />
          <span>Edit</span>
        </ElmButton>
        <ElmButton
          block
          loading={ankiStore.create.loading}
          onClick$={() => ankiStore.create.execute(ankiStore)}
        >
          <ElmMdiIcon d={mdiCreation} />
          <span>New</span>
        </ElmButton>
        <ElmButton
          block
          loading={currentAnki.value == null || ankiStore.review.loading}
          onClick$={() => ankiStore.review.execute(ankiStore)}
        >
          <ElmMdiIcon
            d={
              currentAnki.value?.metadata.is_review_required
                ? mdiAlertDecagram
                : mdiCircleSmall
            }
          />
        </ElmButton>

        <ElmButton
          block
          loading={currentAnki.value == null || currentAnki.value.loading}
          onClick$={() =>
            ankiStore.fetchAnkiBlock(
              ankiStore,
              currentAnki.value?.metadata.page_id,
            )
          }
        >
          <ElmMdiIcon d={mdiRefresh} />
        </ElmButton>
      </div>

      <div class={styles["anki-header"]}>
        <ElmMdiIcon d={mdiSchool} color="#6987b8" />
        <ElmInlineText>Should Learn: {shouldLearnCount.value}</ElmInlineText>
        <ElmMdiIcon d={mdiTrayFull} color="#6987b8" />
        <ElmInlineText>Queue: {count.value}</ElmInlineText>
      </div>

      {!currentAnki.value?.block ? (
        <ElmBlockFallback />
      ) : (
        <>
          <div class={styles["anki-jarkup-container"]}>
            <div class={styles["jarkup-header"]}>
              <ElmMdiIcon d={mdiMessageQuestionOutline} />
              <ElmInlineText>Front</ElmInlineText>
            </div>
            <div class={styles["jarkup-renderer"]}>
              <ElmJarkup jsonComponents={currentAnki.value.block.front} />
            </div>
          </div>

          {isShowingAnswer.value && (
            <>
              <div class={styles["anki-jarkup-container"]}>
                <div class={styles["jarkup-header"]}>
                  <ElmMdiIcon d={mdiMessageAlertOutline} />
                  <ElmInlineText>Back</ElmInlineText>
                </div>
                <div class={styles["jarkup-renderer"]}>
                  <ElmJarkup jsonComponents={currentAnki.value.block.back} />
                </div>
              </div>

              <div class={styles["anki-jarkup-container"]}>
                <div class={styles["jarkup-header"]}>
                  <ElmMdiIcon d={mdiMessageCheckOutline} />
                  <ElmInlineText>Explanation</ElmInlineText>
                </div>
                <div class={styles["jarkup-renderer"]}>
                  <ElmJarkup
                    jsonComponents={currentAnki.value.block.explanation}
                  />
                </div>
              </div>
            </>
          )}
        </>
      )}

      <div class={styles["button-container"]}>
        {!isShowingAnswer.value ? (
          <ElmButton
            block
            onClick$={() => (isShowingAnswer.value = !isShowingAnswer.value)}
          >
            {isShowingAnswer.value ? "Hide Answer" : "Show Answer"}
          </ElmButton>
        ) : (
          <div class={styles["update-button-container"]}>
            {[
              "FORGETFUL",
              "INCORRECT",
              "ALMOST",
              "LUCKY",
              "CORRECT",
              "CONFIDENT",
            ].map((rating, index) => (
              <ElmButton
                key={index}
                block
                onClick$={() =>
                  handleUpdate(currentAnki.value?.metadata.page_id, index)
                }
                primary={index >= 3}
              >
                {rating}
              </ElmButton>
            ))}
          </div>
        )}
      </div>
    </div>
  );
});
