// packages/web-qwik/src/container/bookmark-container.tsx
import {
  $,
  component$,
  useContext,
  useSignal,
  useVisibleTask$,
} from "@qwik.dev/core";

import styles from "./bookmark-container.module.css";
import {
  BookmarkList,
  BookmarkListProps,
} from "~/components/bookmark/bookmark-list";
import { AuthContext } from "~/context/auth-context";
import { openApiClient } from "~/openapi/client";
import {
  ElmButton,
  ElmInlineText,
  ElmTextField,
  useLocalStorage,
} from "@elmethis/qwik";

export const BookmarkContainer = component$(() => {
  const authStore = useContext(AuthContext);

  const { state: bookmarkStore } = useLocalStorage<{
    bookmarks: BookmarkListProps["bookmarks"];
  }>({
    key: "bookmarks",
    initialValue: { bookmarks: [] },
  });

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(async ({ track }) => {
    const accessToken = track(() => authStore.tokens.accessToken);

    if (accessToken) {
      const { data } = await openApiClient.GET("/api/v1/bookmark", {
        params: { header: { Authorization: `Bearer ${accessToken}` } },
      });

      if (data) {
        const bookmarks: BookmarkListProps["bookmarks"] = data.map(
          (bookmark) => {
            return {
              id: bookmark.id,
              icon: bookmark.favicon ?? undefined,
              label: bookmark.name || bookmark.url || "No Title",
              favorite: bookmark.favorite,
              url: bookmark.url || "https://example.com",
              editUrl: bookmark.notion_url,
              tag: bookmark.tag
                ? {
                    id: bookmark.tag.id,
                    name: bookmark.tag.name,
                    color: bookmark.tag.color,
                  }
                : {
                    id: "__untagged__",
                    name: "Untagged",
                    color: "gray",
                  },
            } satisfies BookmarkListProps["bookmarks"][number];
          },
        );

        bookmarkStore.value = { bookmarks };
      }
    }
  });

  const name = useSignal("");
  const url = useSignal("");
  const createBookmarkLoading = useSignal(false);
  const createBookmarkError = useSignal<string | null>(null);

  const handleCreateBookmark = $(async () => {
    createBookmarkError.value = null;

    if (!name.value || !url.value) {
      createBookmarkError.value = "Name and URL are required";
      return;
    }

    const urlPattern = new RegExp(
      "^(https?:\\/\\/)?([\\w-]+\\.)+[\\w-]+(\\/\\S*)?$",
      "i",
    );
    if (!urlPattern.test(url.value)) {
      createBookmarkError.value = "Invalid URL format";
      return;
    }

    let retryCount = 0;

    createBookmarkLoading.value = true;

    while (retryCount < 3) {
      const accessToken = authStore.tokens.accessToken;

      try {
        if (!accessToken) {
          throw new Error("Access token is not available");
        }

        const { data } = await openApiClient.POST("/api/v1/bookmark", {
          params: { header: { Authorization: `Bearer ${accessToken}` } },
          body: { name: name.value, url: url.value },
        });

        if (!data) throw new Error("No data returned from API");

        const newBookmark: BookmarkListProps["bookmarks"][number] = {
          id: data.id,
          icon: data.favicon ?? undefined,
          label: data.name || data.url || "No Title",
          favorite: data.favorite,
          url: data.url || "https://example.com",
          editUrl: data.notion_url,
          tag: data.tag
            ? {
                id: data.tag.id,
                name: data.tag.name,
                color: data.tag.color,
              }
            : {
                id: "__untagged__",
                name: "Untagged",
                color: "gray",
              },
        };

        bookmarkStore.value = {
          bookmarks: [...bookmarkStore.value.bookmarks, newBookmark],
        };

        break;
      } catch (error) {
        retryCount++;
        createBookmarkError.value =
          error instanceof Error ? error.message : String(error);
      } finally {
        createBookmarkLoading.value = false;
      }
    }
  });

  return (
    <div class={styles["bookmark-container"]}>
      <BookmarkList {...bookmarkStore.value} />

      <ElmTextField label="Name" value={name} />
      <ElmTextField label="URL" value={url} />

      <ElmButton
        block
        onClick$={handleCreateBookmark}
        isLoading={createBookmarkLoading.value}
      >
        <span>Create Bookmark</span>
      </ElmButton>

      {createBookmarkError.value && (
        <p>
          <ElmInlineText color="#c56565">
            {createBookmarkError.value}
          </ElmInlineText>
        </p>
      )}
    </div>
  );
});

// packages/web-solid/src/container/bookmark-container.tsx
import { createEffect, createSignal, onCleanup, onMount, Show } from "solid-js";
import { ElmButton, ElmInlineText, ElmTextField } from "@elmethis/solid";

import styles from "./bookmark-container.module.css";
import {
  BookmarkList,
  type BookmarkListProps,
} from "~/components/bookmark/bookmark-list";
import { useAuth } from "~/context/auth-context";
import { openApiClient } from "~/openapi/client";
import { mapBookmarkResponse } from "./bookmark-model";

type Bookmark = BookmarkListProps["bookmarks"][number];
const BOOKMARKS_STORAGE_KEY = "bookmarks";
const URL_PATTERN = /^(https?:\/\/)?([\w-]+\.)+[\w-]+(\/\S*)?$/i;

export const BookmarkContainer = () => {
  const auth = useAuth();
  const [bookmarks, setBookmarks] = createSignal<Bookmark[]>([]);
  const [name, setName] = createSignal("");
  const [url, setUrl] = createSignal("");
  const [createBookmarkLoading, setCreateBookmarkLoading] = createSignal(false);
  const [createBookmarkError, setCreateBookmarkError] = createSignal<
    string | null
  >(null);

  onMount(() => {
    const cached = localStorage.getItem(BOOKMARKS_STORAGE_KEY);
    if (cached) {
      try {
        const value: unknown = JSON.parse(cached);
        if (
          typeof value === "object" &&
          value !== null &&
          "bookmarks" in value &&
          Array.isArray(value.bookmarks)
        ) {
          setBookmarks(value.bookmarks as Bookmark[]);
        }
      } catch {
        // Ignore invalid cache data and replace it with the next valid state.
      }
    }

    createEffect(() => {
      localStorage.setItem(
        BOOKMARKS_STORAGE_KEY,
        JSON.stringify({ bookmarks: bookmarks() }),
      );
    });

    createEffect(() => {
      const accessToken = auth.accessToken();
      if (!accessToken) return;

      const controller = new AbortController();
      void (async () => {
        try {
          const { data } = await openApiClient.GET("/api/v1/bookmark", {
            params: { header: { Authorization: `Bearer ${accessToken}` } },
            signal: controller.signal,
          });

          if (data && !controller.signal.aborted) {
            setBookmarks(data.map(mapBookmarkResponse));
          }
        } catch (error) {
          if (!(error instanceof Error && error.name === "AbortError")) {
            console.error("Failed to fetch bookmarks", error);
          }
        }
      })();

      onCleanup(() => controller.abort());
    });
  });

  const handleCreateBookmark = async () => {
    setCreateBookmarkError(null);

    if (!name() || !url()) {
      setCreateBookmarkError("Name and URL are required");
      return;
    }

    if (!URL_PATTERN.test(url())) {
      setCreateBookmarkError("Invalid URL format");
      return;
    }

    setCreateBookmarkLoading(true);
    try {
      for (let retryCount = 0; retryCount < 3; retryCount += 1) {
        try {
          const accessToken = auth.accessToken();
          if (!accessToken) {
            throw new Error("Access token is not available");
          }

          const { data } = await openApiClient.POST("/api/v1/bookmark", {
            params: { header: { Authorization: `Bearer ${accessToken}` } },
            body: { name: name(), url: url() },
          });

          if (!data) throw new Error("No data returned from API");

          setBookmarks((current) => [...current, mapBookmarkResponse(data)]);
          return;
        } catch (error) {
          setCreateBookmarkError(
            error instanceof Error ? error.message : String(error),
          );
        }
      }
    } finally {
      setCreateBookmarkLoading(false);
    }
  };

  return (
    <div class={styles["bookmark-container"]}>
      <BookmarkList bookmarks={bookmarks()} />

      <ElmTextField
        label="Name"
        value={name()}
        onInput={(event) => setName(event.currentTarget.value)}
      />
      <ElmTextField
        label="URL"
        value={url()}
        onInput={(event) => setUrl(event.currentTarget.value)}
      />

      <ElmButton
        block
        onClick={handleCreateBookmark}
        isLoading={createBookmarkLoading()}
      >
        <span>Create Bookmark</span>
      </ElmButton>

      <Show when={createBookmarkError()} keyed>
        {(error) => (
          <p>
            <ElmInlineText color="#c56565">{error}</ElmInlineText>
          </p>
        )}
      </Show>
    </div>
  );
};
