// packages/web-qwik/src/container/todo-container.tsx
import {
  $,
  component$,
  noSerialize,
  NoSerialize,
  useComputed$,
  useContext,
  useOnWindow,
  useSignal,
  useStore,
  useVisibleTask$,
  type CSSProperties,
} from "@builder.io/qwik";

import styles from "./todo-container.module.css";
import {
  ElmBlockFallback,
  ElmHeading,
  ElmInlineText,
  ElmMdiIcon,
} from "@elmethis/qwik";
import { openApiClient } from "~/openapi/client";
import { AuthContext } from "~/context/auth-context";

import { mdiAlert, mdiSortCalendarAscending, mdiSync } from "@mdi/js";

import { Temporal } from "@js-temporal/polyfill";
import { Todo } from "~/components/todo/todo";

import autoAnimate from "@formkit/auto-animate";

import { paths } from "~/openapi/schema";
import { TodoForm } from "~/components/todo/todo-form";

export interface TodoContainerProps {
  class?: string;

  style?: CSSProperties;
}

type ToDo =
  paths["/api/v1/to-do"]["get"]["responses"]["200"]["content"]["application/json"][number];

type Severity = ToDo["severity"];

export const TodoContainer = component$<TodoContainerProps>(
  ({ class: className, style }) => {
    const authStore = useContext(AuthContext);

    const todoItemContainerRef = useSignal<HTMLElement>();
    const animationController =
      useSignal<NoSerialize<ReturnType<typeof autoAnimate>>>();

    // eslint-disable-next-line qwik/no-use-visible-task
    useVisibleTask$(({ cleanup }) => {
      if (todoItemContainerRef.value) {
        animationController.value = noSerialize(
          autoAnimate(todoItemContainerRef.value),
        );
      }

      cleanup(() => {
        if (animationController.value) {
          animationController.value?.disable();
        }
      });
    });

    const todos = useSignal<ToDo[]>([]);
    const isLoading = useSignal(true);

    const execute = $(async () => {
      isLoading.value = true;
      try {
        await authStore.tokens.refresh(authStore);
        const accessToken = authStore.tokens.accessToken;

        if (accessToken == null) return;

        const res = await openApiClient.GET("/api/v1/to-do", {
          params: {
            header: { Authorization: `Bearer ${accessToken}` },
          },
        });

        todos.value = res.data || [];
      } finally {
        isLoading.value = false;
      }
    });

    // eslint-disable-next-line qwik/no-use-visible-task
    useVisibleTask$(async () => {
      await execute();
    });
    useOnWindow(
      "focus",
      $((event) => {
        if (event.target === window) {
          execute();
        }
      }),
    );

    const updateStateStore = useStore<{
      updatingIds: Array<string>;
    }>({
      updatingIds: [],
    });

    const handleUpdate = $(async (id: string, is_done: boolean) => {
      if (updateStateStore.updatingIds.includes(id)) return;

      updateStateStore.updatingIds.push(id);

      try {
        await authStore.tokens.refresh(authStore);
        const accessToken = authStore.tokens.accessToken;

        if (accessToken == null) return;

        const { data } = await openApiClient.PUT("/api/v1/to-do", {
          params: { header: { Authorization: `Bearer ${accessToken}` } },
          body: { id: id, is_done: is_done },
        });

        if (data) {
          const index = todos.value.findIndex((item) => item.id === id);
          if (index !== -1) {
            todos.value = todos.value.map((item, i) =>
              i === index ? data : item,
            );
          }
        }
      } finally {
        const index = updateStateStore.updatingIds.indexOf(id);
        if (index !== -1) {
          updateStateStore.updatingIds.splice(index, 1);
        }
      }
    });

    const sort = useSignal<"deadline" | "severity">("deadline");

    const handleSort = $((newSort: "deadline" | "severity") => {
      sort.value = newSort;
    });

    const sortedTodos = useComputed$(() => {
      if (!todos.value) return [];

      const sorted = [...todos.value];

      const isDoneSortFn = (
        a: (typeof todos.value)[0],
        b: (typeof todos.value)[0],
      ) => {
        if (a.is_done === b.is_done) return 0;
        return a.is_done ? 1 : -1;
      };

      const deadlineSortFn = (
        a: (typeof todos.value)[0],
        b: (typeof todos.value)[0],
      ) => {
        if (!a.deadline && !b.deadline) return 0;
        if (!a.deadline) return 1;
        if (!b.deadline) return -1;

        return Temporal.PlainDate.from(a.deadline)
          .since(Temporal.PlainDate.from(b.deadline))
          .total({ unit: "day" });
      };

      const severitySortFn = (
        a: (typeof todos.value)[0],
        b: (typeof todos.value)[0],
      ) => {
        const severityOrder: Record<string, number> = {
          Error: 4,
          Warn: 3,
          Info: 2,
          Backlog: 1,
          Unknown: 0,
        };

        return severityOrder[b.severity] - severityOrder[a.severity];
      };

      if (sort.value === "deadline") {
        return sorted.sort(
          (a, b) =>
            isDoneSortFn(a, b) || deadlineSortFn(a, b) || severitySortFn(a, b),
        );
      } else {
        return sorted.sort(
          (a, b) =>
            isDoneSortFn(a, b) || severitySortFn(a, b) || deadlineSortFn(a, b),
        );
      }
    });

    const submit = $(
      async ({ title, severity }: { title: string; severity: Severity }) => {
        await authStore.tokens.refresh(authStore);
        const accessToken = authStore.tokens.accessToken;

        if (accessToken == null) throw new Error("Access token is null");

        const res = await openApiClient.POST("/api/v1/to-do", {
          params: {
            header: { Authorization: `Bearer ${accessToken}` },
          },
          body: {
            title: title,
            severity: severity,
          },
        });

        if (res.data) {
          todos.value = [...todos.value, res.data];
        }
      },
    );

    return (
      <div class={[styles["todo-container"], className]} style={style}>
        <ElmHeading level={2}>To Do</ElmHeading>

        <TodoForm submit$={submit} />

        <div class={styles["sort-container"]}>
          <div
            class={[
              styles["sort-button"],
              { [styles["selected"]]: sort.value === "deadline" },
            ]}
            onClick$={() => handleSort("deadline")}
          >
            <ElmMdiIcon d={mdiSortCalendarAscending} />
            <ElmInlineText>Deadline</ElmInlineText>
          </div>

          <div
            class={[
              styles["sort-button"],
              { [styles["selected"]]: sort.value === "severity" },
            ]}
            onClick$={() => handleSort("severity")}
          >
            <ElmMdiIcon d={mdiAlert} />
            <ElmInlineText>Severity</ElmInlineText>
          </div>

          <ElmMdiIcon
            d={mdiSync}
            size="1.5rem"
            class={[
              styles["sync-icon"],
              { [styles["loading"]]: isLoading.value },
            ]}
            color={isLoading.value ? "#cdb57b" : undefined}
          />
        </div>

        <div ref={todoItemContainerRef} class={styles["todo-item-container"]}>
          {todos.value.length === 0 ? (
            <ElmBlockFallback></ElmBlockFallback>
          ) : (
            sortedTodos.value?.map((item) => (
              <Todo
                key={`${item.id}-${item.is_done}`}
                id={item.id}
                title={item.title}
                url={item.url}
                deadline={item.deadline}
                severity={item.severity}
                is_recurring={item.is_recurring}
                is_done={item.is_done}
                onClick$={handleUpdate}
                isLoading={updateStateStore.updatingIds.includes(item.id)}
              />
            ))
          )}
        </div>
      </div>
    );
  },
);

// packages/web-solid/src/container/todo-container.tsx
import {
  createMemo,
  createSignal,
  For,
  onCleanup,
  onMount,
  Show,
  type JSX,
} from "solid-js";
import {
  ElmBlockFallback,
  ElmHeading,
  ElmInlineText,
  ElmMdiIcon,
} from "@elmethis/solid";
import autoAnimate from "@formkit/auto-animate";
import { mdiAlert, mdiSortCalendarAscending, mdiSync } from "@mdi/js";

import styles from "./todo-container.module.css";
import { Todo } from "~/components/todo/todo";
import { TodoForm } from "~/components/todo/todo-form";
import { useAuth } from "~/context/auth-context";
import { openApiClient } from "~/openapi/client";
import { sortTodos, type ToDo, type TodoSort } from "./todo-sort";

export interface TodoContainerProps {
  class?: string;
  style?: JSX.CSSProperties;
}

type Severity = ToDo["severity"];

export const TodoContainer = (props: TodoContainerProps) => {
  const auth = useAuth();
  const [todos, setTodos] = createSignal<ToDo[]>([]);
  const [isLoading, setIsLoading] = createSignal(true);
  const [updatingIds, setUpdatingIds] = createSignal<string[]>([]);
  const [sort, setSort] = createSignal<TodoSort>("deadline");
  const sortedTodos = createMemo(() => sortTodos(todos(), sort()));
  let todoItemContainerRef!: HTMLDivElement;
  let fetchController: AbortController | undefined;

  const execute = async () => {
    fetchController?.abort();
    const controller = new AbortController();
    fetchController = controller;
    setIsLoading(true);
    try {
      await auth.refresh();
      const accessToken = auth.accessToken();
      if (accessToken == null) return;

      const { data } = await openApiClient.GET("/api/v1/to-do", {
        params: {
          header: { Authorization: `Bearer ${accessToken}` },
        },
        signal: controller.signal,
      });
      if (!controller.signal.aborted) setTodos(data || []);
    } catch (error) {
      if (!(error instanceof Error && error.name === "AbortError")) {
        console.error("Failed to fetch todos", error);
      }
    } finally {
      if (fetchController === controller) {
        fetchController = undefined;
        setIsLoading(false);
      }
    }
  };

  onMount(() => {
    const animationController = autoAnimate(todoItemContainerRef);
    const handleFocus = (event: FocusEvent) => {
      if (event.target === window) void execute();
    };

    window.addEventListener("focus", handleFocus);
    void execute();

    onCleanup(() => {
      window.removeEventListener("focus", handleFocus);
      fetchController?.abort();
      if (animationController.destroy) animationController.destroy();
      else animationController.disable();
    });
  });

  const handleUpdate = async (id: string, isDone: boolean) => {
    if (updatingIds().includes(id)) return;
    setUpdatingIds((current) => [...current, id]);

    try {
      await auth.refresh();
      const accessToken = auth.accessToken();
      if (accessToken == null) return;

      const { data } = await openApiClient.PUT("/api/v1/to-do", {
        params: { header: { Authorization: `Bearer ${accessToken}` } },
        body: { id, is_done: isDone },
      });

      if (data) {
        setTodos((current) =>
          current.map((item) => (item.id === id ? data : item)),
        );
      }
    } finally {
      setUpdatingIds((current) => current.filter((item) => item !== id));
    }
  };

  const submit = async ({
    title,
    severity,
    deadline,
  }: {
    title: string;
    severity: Severity;
    deadline?: string;
  }) => {
    await auth.refresh();
    const accessToken = auth.accessToken();
    if (accessToken == null) throw new Error("Access token is null");

    const { data } = await openApiClient.POST("/api/v1/to-do", {
      params: {
        header: { Authorization: `Bearer ${accessToken}` },
      },
      body: { title, severity, deadline },
    });

    if (data) setTodos((current) => [...current, data]);
  };

  return (
    <div
      class={`${styles["todo-container"]} ${props.class ?? ""}`}
      style={props.style}
    >
      <ElmHeading level={2}>To Do</ElmHeading>

      <TodoForm submit={submit} />

      <div class={styles["sort-container"]}>
        <div
          class={styles["sort-button"]}
          classList={{ [styles.selected]: sort() === "deadline" }}
          onClick={() => setSort("deadline")}
        >
          <ElmMdiIcon d={mdiSortCalendarAscending} />
          <ElmInlineText>Deadline</ElmInlineText>
        </div>

        <div
          class={styles["sort-button"]}
          classList={{ [styles.selected]: sort() === "severity" }}
          onClick={() => setSort("severity")}
        >
          <ElmMdiIcon d={mdiAlert} />
          <ElmInlineText>Severity</ElmInlineText>
        </div>

        <ElmMdiIcon
          d={mdiSync}
          size="1.5rem"
          class={`${styles["sync-icon"]} ${isLoading() ? styles.loading : ""}`}
          color={isLoading() ? "#cdb57b" : undefined}
        />
      </div>

      <div ref={todoItemContainerRef} class={styles["todo-item-container"]}>
        <Show when={todos().length > 0} fallback={<ElmBlockFallback />}>
          <For each={sortedTodos()}>
            {(item) => (
              <Todo
                id={item.id}
                title={item.title}
                url={item.url}
                deadline={item.deadline}
                severity={item.severity}
                is_recurring={item.is_recurring}
                is_done={item.is_done}
                onClick={handleUpdate}
                isLoading={updatingIds().includes(item.id)}
              />
            )}
          </For>
        </Show>
      </div>
    </div>
  );
};
