// packages/web-qwik/src/context/anki-context.tsx
import {
  $,
  createContextId,
  QRL,
  useContext,
  useContextProvider,
  useStore,
  useVisibleTask$,
} from "@builder.io/qwik";
import { openApiClient } from "~/openapi/client";
import { paths } from "~/openapi/schema";
import { AuthContext } from "./auth-context";
import { ElmJarkupProps } from "@elmethis/qwik";

type AnkiMeta =
  paths["/api/v1/anki/{page_id}"]["get"]["responses"]["200"]["content"]["application/json"][number];

type AnkiBlock = {
  back: ElmJarkupProps["jsonComponents"];
  explanation: ElmJarkupProps["jsonComponents"];
  front: ElmJarkupProps["jsonComponents"];
};

export interface AnkiStore {
  error: string | null;

  ankiList: {
    data: Array<{
      metadata: AnkiMeta;
      block: AnkiBlock | null;
      loading: boolean;
    }>;
    currentIndex: number | null;
    loading: boolean;
  };

  updateAnkiByPerformanceRating?: QRL<
    (
      ankiStore: AnkiStore,
      pageId: string,
      performanceRating: number,
    ) => Promise<void>
  >;

  fetchAnkiBlock: QRL<
    (store: AnkiStore, pageId?: string, signal?: AbortSignal) => Promise<void>
  >;

  create: {
    execute: QRL<(store: AnkiStore) => Promise<void>>;
    loading: boolean;
  };

  review: {
    execute: QRL<(store: AnkiStore) => Promise<void>>;
    loading: boolean;
  };
}

export const AnkiContext = createContextId<AnkiStore>("anki");

export const useAnkiContextProvider = () => {
  const authStore = useContext(AuthContext);

  const ankiStore = useStore<AnkiStore>({
    error: null,

    ankiList: {
      data: [],
      currentIndex: null,
      loading: false,
    },

    updateAnkiByPerformanceRating: $(
      async (store: AnkiStore, pageId: string, performanceRating: number) => {
        const ankiRef = store.ankiList.data.find(
          (anki) => anki.metadata.page_id === pageId,
        );

        try {
          if (!ankiRef)
            throw new Error(
              `Anki with page_id ${pageId} not found in the list.`,
            );

          await authStore.tokens.refresh(authStore);

          const maxInterval = 365 / 4;
          const minInterval = 0.5;

          let newEaseFactor: number;
          let newRepetitionCount: number;

          if (performanceRating < 3) {
            newEaseFactor = Math.max(1.3, ankiRef.metadata.ease_factor * 0.85);
            newRepetitionCount = 0;
          } else {
            newEaseFactor =
              ankiRef.metadata.ease_factor +
              0.1 -
              (5 - performanceRating) * (0.08 + (5 - performanceRating) * 0.02);
            newRepetitionCount = ankiRef.metadata.repetition_count + 1;
          }

          let newInterval;
          if (performanceRating === 0) {
            newInterval = minInterval;
          } else if (performanceRating === 1) {
            newInterval = minInterval;
          } else if (performanceRating === 2) {
            newInterval = Math.max(minInterval, newRepetitionCount);
          } else {
            let multiplier = 1;
            if (performanceRating === 3) {
              multiplier = 1;
            } else if (performanceRating === 4) {
              multiplier = 1.5;
            } else if (performanceRating === 5) {
              multiplier = 2;
            }
            newInterval = Math.min(
              maxInterval,
              Math.pow(newEaseFactor, newRepetitionCount) * multiplier,
            );
          }

          const newNextReviewAt = new Date(
            Date.now() + newInterval * 24 * 60 * 60 * 1000,
          ).toISOString();

          ankiRef.metadata.ease_factor = newEaseFactor;
          ankiRef.metadata.repetition_count = newRepetitionCount;
          ankiRef.metadata.next_review_at = newNextReviewAt;

          const payload = {
            ease_factor: newEaseFactor,
            repetition_count: newRepetitionCount,
            next_review_at: newNextReviewAt,
          };

          (async () => {
            await openApiClient.PUT(`/api/v1/anki/{page_id}`, {
              params: {
                header: {
                  Authorization: `Bearer ${authStore.tokens.accessToken}`,
                },
                path: { page_id: ankiRef!.metadata.page_id },
              },
              body: payload,
            });
          })();

          if (store.ankiList.currentIndex != null) {
            store.ankiList.currentIndex = store.ankiList.currentIndex + 1;
          } else {
            store.ankiList.currentIndex = 0;
          }
        } catch (error) {
          if (ankiRef)
            store.error =
              "Failed to fetch Anki block. " +
              (error instanceof Error ? error.message : String(error));
        }
      },
    ),

    fetchAnkiBlock: $(async (store: AnkiStore, pageId?: string, signal?: AbortSignal) => {
      const ankiRef = store.ankiList.data.find(
        (anki) => anki.metadata.page_id === pageId,
      );

      try {
        if (!pageId)
          throw new Error("Page ID is required to fetch Anki block.");
        if (!ankiRef)
          throw new Error(`Anki with page_id ${pageId} not found in the list.`);

        // Prevent multiple fetches for the same block
        if (ankiRef.loading) return;

        ankiRef.loading = true;

        await authStore.tokens.refresh(authStore);

        const { data: ankiBlockData } = await openApiClient.GET(
          `/api/v1/anki/block/{page_id}`,
          {
            params: {
              header: {
                Authorization: `Bearer ${authStore.tokens.accessToken}`,
              },
              path: { page_id: pageId },
            },
            signal,
          },
        );

        if (ankiBlockData) ankiRef.block = ankiBlockData as AnkiBlock;
      } catch (error) {
        if (!(error instanceof Error && error.name === "AbortError")) {
          store.error =
            "Failed to fetch Anki block. " +
            (error instanceof Error ? error.message : String(error));
        }
      } finally {
        if (ankiRef && !signal?.aborted) ankiRef.loading = false;
      }
    }),

    create: {
      execute: $(async (store: AnkiStore) => {
        store.create.loading = true;

        try {
          await authStore.tokens.refresh(authStore);

          const { data } = await openApiClient.POST("/api/v1/anki", {
            params: {
              header: {
                Authorization: `Bearer ${authStore.tokens.accessToken}`,
              },
            },
            body: {},
          });

          if (data == null) {
            throw new Error("No data returned from API");
          } else {
            const a = document.createElement("a");
            a.href = data.url.replace(/https?\/\//, "notionrs://");
            a.target = "_blank";
            a.rel = "noopener noreferrer";
            a.click();
          }
        } catch (error) {
          store.error =
            "Failed to create new Anki. " +
            (error instanceof Error ? error.message : String(error));
        } finally {
          store.create.loading = false;
        }
      }),
      loading: false,
    },

    review: {
      execute: $(async (store: AnkiStore) => {
        store.review.loading = true;
        try {
          if (store.ankiList.currentIndex == null) {
            throw new Error("No current Anki to review");
          }

          const currentAnki = store.ankiList.data[store.ankiList.currentIndex];

          await authStore.tokens.refresh(authStore);

          const res = await openApiClient.PUT(`/api/v1/anki/{page_id}`, {
            params: {
              header: {
                Authorization: `Bearer ${authStore.tokens.accessToken}`,
              },
              path: {
                page_id: currentAnki.metadata.page_id,
              },
            },
            body: {
              is_review_required: !currentAnki.metadata.is_review_required,
            },
          });

          if (!res.data) {
            throw new Error("No data returned from API");
          }

          currentAnki.metadata.is_review_required = res.data.is_review_required;
        } catch (error) {
          store.error =
            "Failed to review Anki. " +
            (error instanceof Error ? error.message : String(error));
        } finally {
          store.review.loading = false;
        }
      }),
      loading: false,
    },
  });

  useContextProvider(AnkiContext, ankiStore);

  const fetchAnkiList = $(async (controller?: AbortController) => {
    ankiStore.ankiList.loading = true;

    try {
      await authStore.tokens.refresh(authStore);

      const { data: ankiListData } = await openApiClient.GET("/api/v1/anki", {
        params: {
          header: {
            Authorization: `Bearer ${authStore.tokens.accessToken}`,
          },
        },
        signal: controller?.signal,
      });

      if (ankiListData)
        ankiStore.ankiList.data = ankiListData.map((anki) => ({
          metadata: anki,
          block: null,
          loading: false,
          error: null,
        }));

      if (ankiListData && ankiListData.length > 0)
        ankiStore.ankiList.currentIndex = 0;
    } catch (error) {
      if (!(error instanceof Error && error.name === "AbortError")) {
        ankiStore.error =
          "Failed to fetch Anki list. " +
          (error instanceof Error ? error.message : String(error));
      }
    } finally {
      if (!controller?.signal.aborted) {
        ankiStore.ankiList.loading = false;
      }
    }
  });

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(({ cleanup }) => {
    const controller = new AbortController();
    cleanup(() => controller.abort());

    fetchAnkiList(controller);
  });

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(({ cleanup, track }) => {
    const controller = new AbortController();
    cleanup(() => controller.abort());

    const currentIndex = track(() => ankiStore.ankiList.currentIndex);

    if (currentIndex === null) return;

    const currentAnkiRef = ankiStore.ankiList.data[currentIndex];
    if (currentAnkiRef)
      ankiStore.fetchAnkiBlock(ankiStore, currentAnkiRef.metadata.page_id, controller.signal);

    const nextAnkiRef = ankiStore.ankiList.data[currentIndex + 1];
    if (nextAnkiRef)
      ankiStore.fetchAnkiBlock(ankiStore, nextAnkiRef.metadata.page_id, controller.signal);

    const nextNextAnkiRef = ankiStore.ankiList.data[currentIndex + 2];
    if (nextNextAnkiRef)
      ankiStore.fetchAnkiBlock(ankiStore, nextNextAnkiRef.metadata.page_id, controller.signal);
  });
};

// packages/web-solid/src/context/anki-context.tsx
import {
  createContext,
  createEffect,
  onCleanup,
  untrack,
  useContext,
  type ParentProps,
} from "solid-js";
import { createStore } from "solid-js/store";

import { openApiClient } from "~/openapi/client";
import type { paths } from "~/openapi/schema";
import { useAuth } from "./auth-context";

type AnkiMeta =
  paths["/api/v1/anki/{page_id}"]["get"]["responses"]["200"]["content"]["application/json"];

interface AnkiBlock {
  back: unknown;
  explanation: unknown;
  front: unknown;
}

interface AnkiItem {
  metadata: AnkiMeta;
  block: AnkiBlock | null;
  loading: boolean;
}

interface AnkiState {
  error: string | null;
  ankiList: {
    data: AnkiItem[];
    currentIndex: number | null;
    loading: boolean;
  };
  create: { loading: boolean };
  review: { loading: boolean };
}

interface AnkiContextValue {
  state: AnkiState;
  fetchList: (signal?: AbortSignal) => Promise<void>;
  fetchBlock: (
    pageId?: string,
    signal?: AbortSignal,
    force?: boolean,
  ) => Promise<void>;
  updateByRating: (pageId: string, rating: number) => Promise<void>;
  create: () => Promise<void>;
  review: () => Promise<void>;
}

const AnkiContext = createContext<AnkiContextValue>();

export const AnkiProvider = (props: ParentProps) => {
  const auth = useAuth();
  const [state, setState] = createStore<AnkiState>({
    error: null,
    ankiList: { data: [], currentIndex: null, loading: false },
    create: { loading: false },
    review: { loading: false },
  });

  const setError = (prefix: string, error: unknown) => {
    if (error instanceof Error && error.name === "AbortError") return;
    setState(
      "error",
      `${prefix}${error instanceof Error ? error.message : String(error)}`,
    );
  };

  const fetchList = async (signal?: AbortSignal) => {
    setState("ankiList", "loading", true);
    try {
      await auth.refresh();
      const { data } = await openApiClient.GET("/api/v1/anki", {
        params: {
          header: { Authorization: `Bearer ${auth.accessToken()}` },
        },
        signal,
      });
      if (data) {
        setState(
          "ankiList",
          "data",
          data.map((metadata) => ({ metadata, block: null, loading: false })),
        );
        setState("ankiList", "currentIndex", data.length > 0 ? 0 : null);
      }
    } catch (error) {
      setError("Failed to fetch Anki list. ", error);
    } finally {
      if (!signal?.aborted) setState("ankiList", "loading", false);
    }
  };

  const fetchBlock = async (
    pageId?: string,
    signal?: AbortSignal,
    force = false,
  ) => {
    const index = state.ankiList.data.findIndex(
      (item) => item.metadata.page_id === pageId,
    );
    if (!pageId || index < 0) return;
    if (state.ankiList.data[index].loading) return;
    if (state.ankiList.data[index].block && !force) return;

    setState("ankiList", "data", index, "loading", true);
    try {
      await auth.refresh();
      const { data } = await openApiClient.GET("/api/v1/anki/block/{page_id}", {
        params: {
          header: { Authorization: `Bearer ${auth.accessToken()}` },
          path: { page_id: pageId },
        },
        signal,
      });
      if (data) setState("ankiList", "data", index, "block", data as AnkiBlock);
    } catch (error) {
      setError("Failed to fetch Anki block. ", error);
    } finally {
      if (!signal?.aborted) {
        setState("ankiList", "data", index, "loading", false);
      }
    }
  };

  const updateByRating = async (pageId: string, rating: number) => {
    const index = state.ankiList.data.findIndex(
      (item) => item.metadata.page_id === pageId,
    );
    if (index < 0) return;

    try {
      await auth.refresh();
      const current = state.ankiList.data[index].metadata;
      const repetitionCount = rating < 3 ? 0 : current.repetition_count + 1;
      const easeFactor =
        rating < 3
          ? Math.max(1.3, current.ease_factor * 0.85)
          : current.ease_factor +
            0.1 -
            (5 - rating) * (0.08 + (5 - rating) * 0.02);
      const multiplier = rating === 4 ? 1.5 : rating === 5 ? 2 : 1;
      const interval =
        rating <= 1
          ? 0.5
          : rating === 2
            ? Math.max(0.5, repetitionCount)
            : Math.min(
                91.25,
                Math.pow(easeFactor, repetitionCount) * multiplier,
              );
      const nextReviewAt = new Date(
        Date.now() + interval * 24 * 60 * 60 * 1000,
      ).toISOString();

      setState(
        "ankiList",
        "data",
        index,
        "metadata",
        "ease_factor",
        easeFactor,
      );
      setState(
        "ankiList",
        "data",
        index,
        "metadata",
        "repetition_count",
        repetitionCount,
      );
      setState(
        "ankiList",
        "data",
        index,
        "metadata",
        "next_review_at",
        nextReviewAt,
      );

      void openApiClient
        .PUT("/api/v1/anki/{page_id}", {
          params: {
            header: { Authorization: `Bearer ${auth.accessToken()}` },
            path: { page_id: pageId },
          },
          body: {
            ease_factor: easeFactor,
            repetition_count: repetitionCount,
            next_review_at: nextReviewAt,
          },
        })
        .then(({ error }) => {
          if (error) setError("Failed to persist Anki update. ", error);
        })
        .catch((error) => setError("Failed to persist Anki update. ", error));
      setState(
        "ankiList",
        "currentIndex",
        (state.ankiList.currentIndex ?? -1) + 1,
      );
    } catch (error) {
      setError("Failed to update Anki. ", error);
    }
  };

  const create = async () => {
    setState("create", "loading", true);
    try {
      await auth.refresh();
      const { data } = await openApiClient.POST("/api/v1/anki", {
        params: {
          header: { Authorization: `Bearer ${auth.accessToken()}` },
        },
        body: {},
      });
      if (!data) throw new Error("No data returned from API");
      window.open(
        data.url.replace(/^https?:\/\//, "notionrs://"),
        "_blank",
        "noopener,noreferrer",
      );
    } catch (error) {
      setError("Failed to create new Anki. ", error);
    } finally {
      setState("create", "loading", false);
    }
  };

  const review = async () => {
    const index = state.ankiList.currentIndex;
    if (index == null || !state.ankiList.data[index]) return;
    setState("review", "loading", true);
    try {
      await auth.refresh();
      const current = state.ankiList.data[index];
      const { data } = await openApiClient.PUT("/api/v1/anki/{page_id}", {
        params: {
          header: { Authorization: `Bearer ${auth.accessToken()}` },
          path: { page_id: current.metadata.page_id },
        },
        body: { is_review_required: !current.metadata.is_review_required },
      });
      if (!data) throw new Error("No data returned from API");
      setState(
        "ankiList",
        "data",
        index,
        "metadata",
        "is_review_required",
        data.is_review_required,
      );
    } catch (error) {
      setError("Failed to review Anki. ", error);
    } finally {
      setState("review", "loading", false);
    }
  };

  createEffect(() => {
    const accessToken = auth.accessToken();
    if (typeof window === "undefined" || !accessToken) return;
    const controller = new AbortController();
    untrack(() => void fetchList(controller.signal));
    onCleanup(() => controller.abort());
  });

  createEffect(() => {
    const currentIndex = state.ankiList.currentIndex;
    if (typeof window === "undefined" || currentIndex == null) return;
    const pageIds = [currentIndex, currentIndex + 1, currentIndex + 2]
      .map((index) => state.ankiList.data[index]?.metadata.page_id)
      .filter((pageId): pageId is string => pageId != null);
    const controller = new AbortController();
    untrack(() => {
      for (const pageId of pageIds) void fetchBlock(pageId, controller.signal);
    });
    onCleanup(() => controller.abort());
  });

  return (
    <AnkiContext.Provider
      value={{ state, fetchList, fetchBlock, updateByRating, create, review }}
    >
      {props.children}
    </AnkiContext.Provider>
  );
};

export const useAnki = () => {
  const context = useContext(AnkiContext);
  if (!context) throw new Error("useAnki must be used within AnkiProvider");
  return context;
};
